name: Run Tests

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --silent --frozen-lockfile
      - name: Setup DynamoDB Local
        uses: rrainn/dynamodb-action@v3.0.0
        with:
          sharedDb: true
          port: 8000
          cors: '*'
      - run: yarn test
        env:
          IS_OFFLINE: true
          AWS_REGION: local-env
          AWS_ACCESS_KEY_ID: notused
          AWS_SECRET_ACCESS_KEY: notused
